const adsPageContent = {
  "gk": {
    "general": {
      "anxiety": {
        "adgroup": "GK - General - Anxiety",
        "campaign": "IO_Delhi",
        "service": "General",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Experts in Anxiety Relief",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/anxiety/gk",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized anxiety diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed\n",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "GK - General - Depression",
        "campaign": "IO_Delhi",
        "service": "General",
        "condition": "Depression",
        "headline_1_(pinned)": "Depression Experts for you",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/depression/gk",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert clinical team.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized depression diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "GK - General - OCD",
        "campaign": "IO_Delhi",
        "service": "General",
        "condition": "OCD",
        "headline_1_(pinned)": "Experienced in Treating OCD",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/ocd/gk",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our dedicated clinical team.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized OCD diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    },
    "psychiatrist": {
      "anxiety": {
        "adgroup": "GK - Psychiatrist - Anxiety",
        "campaign": "IO_Delhi",
        "service": "Psychiatrist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Psychiatrists | Anxiety Relief",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800 / session",
        "headline_3": "Expert Anxiety Treatment",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |   ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/anxiety/gk",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert psychiatrists.\n",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our experienced psychiatrists provide:\nPersonalized anxiety diagnosis\nCustomized treatment plans including medication if needed\nSafe and confidential consultations",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "GK - Psychiatrist - Depression",
        "campaign": "IO_Delhi",
        "service": "Psychiatrist",
        "condition": "Depression",
        "headline_1_(pinned)": "Psychiatrists for Depression.",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800 / session",
        "headline_3": "Effective Depression Treatment",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |   ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/depression/gk",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our experienced psychiatrists. ",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized depression diagnosis\nCustomized treatment plans, including medication management\nSafe and confidential consultations",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "GK - Psychiatrist - General",
        "campaign": "IO_Delhi",
        "service": "Psychiatrist",
        "condition": "General",
        "headline_1_(pinned)": "Experienced Psychiatrists",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800 / session",
        "headline_3": "Expertise for Every Condition",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |   ",
        "description_2__(pinned)": "Whatever your needs, our team supports you at our Greater Kailash Clinic in Delhi NCR",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/general/gk",
        "lp_hero_title": "Are you looking for an experienced psychiatrist?",
        "lp_hero_subtitle": "Experience individualized care from experienced psychiatrists committed to improving your quality of life.\n\nWe help with:\nAnxiety | Depression | OCD | Bipolar Disorder | PTSD | Schizophrenia |\nand more. ",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized condition diagnosis\nCustomized treatment plans, including medication if needed\nSafe and confidential consultations",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "GK - Psychiatrist - OCD",
        "campaign": "IO_Delhi",
        "service": "Psychiatrist",
        "condition": "OCD",
        "headline_1_(pinned)": "Experienced OCD Psychiatrists",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800 / session",
        "headline_3": "Effective OCD Treatment Plan",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |   ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/ocd/gk",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our expert psychiatrists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized OCD diagnosis\nCustomized treatment plans, including medication management\nSafe and confidential consultations",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    },
    "psychologist": {
      "anxiety": {
        "adgroup": "GK - Psychologist - Anxiety",
        "campaign": "IO_Delhi",
        "service": "Psychologist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Psychologists | Anxiety Relief",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/anxiety/gk",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert psychiatrists.\n",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized anxiety diagnosis\nClinical Assessments\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "GK - Psychologist - Depression",
        "campaign": "IO_Delhi",
        "service": "Psychologist",
        "condition": "Depression",
        "headline_1_(pinned)": "Psychologists for Depression.",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/depression/gk",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our experienced psychologists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized depression diagnosis\nClinical Assessments\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "GK - Psychologist - General",
        "campaign": "IO_Delhi",
        "service": "Psychologist",
        "condition": "General",
        "headline_1_(pinned)": "Expert Psychologists for You",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team supports you at our Greater Kailash Clinic in Delhi NCR",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/general/gk",
        "lp_hero_title": "Are you looking for an experienced psychologist?",
        "lp_hero_subtitle": "Experience personalized care from our expert psychologists for various mental health challenges.\n\nWe help with:\nAnxiety | Depression | OCD | Sleep Disorders | Trauma | PTSD | ADHD\nand more. ",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized condition diagnosis\nClinical Assessments\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "GK - Psychologist - OCD",
        "campaign": "IO_Delhi",
        "service": "Psychologist",
        "condition": "OCD",
        "headline_1_(pinned)": "Expert Psychologists for OCD.",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/ocd/gk",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our expert psychologists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized OCD diagnosis\nClinical Assessments\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    },
    "therapist": {
      "anxiety": {
        "adgroup": "GK - Therapist - Anxiety",
        "campaign": "IO_Delhi",
        "service": "Therapist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Therapists for Anxiety Help.",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/anxiety/gk",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our experienced therapists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized anxiety diagnosis\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "GK - Therapist - Depression",
        "campaign": "IO_Delhi",
        "service": "Therapist",
        "condition": "Depression",
        "headline_1_(pinned)": "Expert Therapists | Depression",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/depression/gk",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert therapists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized depression diagnosis\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "GK - Therapist - General",
        "campaign": "IO_Delhi",
        "service": "Therapist",
        "condition": "General",
        "headline_1_(pinned)": "Experienced Therapists for You",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team supports you at our Greater Kailash Clinic in Delhi NCR",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/general/gk",
        "lp_hero_title": "Are you looking for an experienced therapist?",
        "lp_hero_subtitle": "Experience personalized care from our compassionate therapists for various mental health challenges.\n\nWe help with:\nAnxiety | Depression | OCD | Sleep Disorders | Trauma | PTSD | ADHD\nand more.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized condition diagnosis\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "GK - Therapist - OCD",
        "campaign": "IO_Delhi",
        "service": "Therapist",
        "condition": "OCD",
        "headline_1_(pinned)": "Dedicated Therapist | OCD Care",
        "headline_2_(pinned)": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/ocd/gk",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our dedicated therapists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized OCD diagnosis\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    }
  },
  "hb": {
    "general": {
      "anxiety": {
        "adgroup": "Hebbal - General - Anxiety",
        "campaign": "IO_Hebbal",
        "service": "General",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Experts in Anxiety Relief",
        "headline_2_(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with anxiety at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/general/anxiety/hb",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized anxiety diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed\n",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Hebbal - General - Depression",
        "campaign": "IO_Hebbal",
        "service": "General",
        "condition": "Depression",
        "headline_1_(pinned)": "Depression Experts for you",
        "headline_2_(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/general/depression/hb",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert clinical team.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized depression diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Hebbal - General - OCD",
        "campaign": "IO_Hebbal",
        "service": "General",
        "condition": "OCD",
        "headline_1_(pinned)": "Experienced in Treating OCD",
        "headline_2_(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/general/ocd/hb",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our dedicated clinical team.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized OCD diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    },
    "psychologist": {
      "anxiety": {
        "adgroup": "Hebbal - Psychologist - Anxiety",
        "campaign": "IO_Hebbal",
        "service": "Psychologist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Psychologists | Anxiety Relief",
        "headline_2_(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with anxiety at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/anxiety/hb",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert psychiatrists.\n",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized anxiety diagnosis\nClinical Assessments\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Hebbal - Psychologist - Depression",
        "campaign": "IO_Hebbal",
        "service": "Psychologist",
        "condition": "Depression",
        "headline_1_(pinned)": "Psychologists for Depression.",
        "headline_2_(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/depression/hb",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our experienced psychologists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized depression diagnosis\nClinical Assessments\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "Hebbal - Psychologist - General",
        "campaign": "IO_Hebbal",
        "service": "Psychologist",
        "condition": "General",
        "headline_1_(pinned)": "Expert Psychologists for You",
        "headline_2_(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team is there for you at our Hebbal Clinic in Aster CMI Hospital.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/general/hb",
        "lp_hero_title": "Are you looking for an experienced psychologist?",
        "lp_hero_subtitle": "Experience personalized care from our expert psychologists for various mental health challenges.\n\nWe help with:\nAnxiety | Depression | OCD | Sleep Disorders | Trauma | PTSD | ADHD\nand more. ",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized condition diagnosis\nClinical Assessments\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Hebbal - Psychologist - OCD",
        "campaign": "IO_Hebbal",
        "service": "Psychologist",
        "condition": "OCD",
        "headline_1_(pinned)": "Expert Psychologists for OCD.",
        "headline_2_(pinned)": "Hebbal (AsterCMI) | Rs1800/hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/ocd/hb",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our expert psychologists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized OCD diagnosis\nClinical Assessments\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    },
    "therapist": {
      "anxiety": {
        "adgroup": "Hebbal - Therapist - Anxiety",
        "campaign": "IO_Hebbal",
        "service": "Therapist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Therapists for Anxiety Help.",
        "headline_2_(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with anxiety at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/anxiety/hb",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our experienced therapists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized anxiety diagnosis\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Hebbal - Therapist - Depression",
        "campaign": "IO_Hebbal",
        "service": "Therapist",
        "condition": "Depression",
        "headline_1_(pinned)": "Expert Therapists | Depression",
        "headline_2_(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/depression/hb",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert therapists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized depression diagnosis\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "Hebbal - Therapist - General",
        "campaign": "IO_Hebbal",
        "service": "Therapist",
        "condition": "General",
        "headline_1_(pinned)": "Experienced Therapists for You",
        "headline_2_(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team is there for you at our Hebbal Clinic in Aster CMI Hospital.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/general/hb",
        "lp_hero_title": "Are you looking for an experienced therapist?",
        "lp_hero_subtitle": "Experience personalized care from our compassionate therapists for various mental health challenges.\n\nWe help with:\nAnxiety | Depression | OCD | Sleep Disorders | Trauma | PTSD | ADHD\nand more.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized condition diagnosis\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Hebbal - Therapist - OCD",
        "campaign": "IO_Hebbal",
        "service": "Therapist",
        "condition": "OCD",
        "headline_1_(pinned)": "Dedicated Therapist | OCD Care",
        "headline_2_(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/ocd/hb",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our dedicated therapists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized OCD diagnosis\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    }
  },
  "wf": {
    "general": {
      "anxiety": {
        "adgroup": "Whitefield - General - Anxiety",
        "campaign": "IO_Whitefield",
        "service": "General",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Experts in Anxiety Relief",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/anxiety/wf",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized anxiety diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed\n",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Whitefield - General - Depression",
        "campaign": "IO_Whitefield",
        "service": "General",
        "condition": "Depression",
        "headline_1_(pinned)": "Depression Experts for you",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/depression/wf",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert clinical team.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized depression diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Whitefield - General - OCD",
        "campaign": "IO_Whitefield",
        "service": "General",
        "condition": "OCD",
        "headline_1_(pinned)": "Experienced in Treating OCD",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Whitefield Clinic on Old Airport Road",
        "new_landing_page_url": "https://mindfultms.in/ads/general/ocd/wf",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our dedicated clinical team.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized OCD diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    },
    "psychiatrist": {
      "anxiety": {
        "adgroup": "Whitefield - Psychiatrist - Anxiety",
        "campaign": "IO_Whitefield",
        "service": "Psychiatrist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Psychiatrists | Anxiety Relief",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Expert Anxiety Treatment",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |   ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/anxiety/wf",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert psychiatrists.\n",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our experienced psychiatrists provide:\nPersonalized anxiety diagnosis\nCustomized treatment plans including medication if needed\nSafe and confidential consultations",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Whitefield - Psychiatrist - Depression",
        "campaign": "IO_Whitefield",
        "service": "Psychiatrist",
        "condition": "Depression",
        "headline_1_(pinned)": "Psychiatrists for Depression.",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Effective Depression Treatment",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |   ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/depression/wf",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our experienced psychiatrists. ",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized depression diagnosis\nCustomized treatment plans, including medication management\nSafe and confidential consultations",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "Whitefield - Psychiatrist - General",
        "campaign": "IO_Whitefield",
        "service": "Psychiatrist",
        "condition": "General",
        "headline_1_(pinned)": "Experienced Psychiatrists",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Expertise for Every Condition",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |   ",
        "description_2__(pinned)": "Whatever your needs, our team is there for you at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/general/wf",
        "lp_hero_title": "Are you looking for an experienced psychiatrist?",
        "lp_hero_subtitle": "Experience individualized care from experienced psychiatrists committed to improving your quality of life.\n\nWe help with:\nAnxiety | Depression | OCD | Bipolar Disorder | PTSD | Schizophrenia |\nand more. ",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized condition diagnosis\nCustomized treatment plans, including medication if needed\nSafe and confidential consultations",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Whitefield - Psychiatrist - OCD",
        "campaign": "IO_Whitefield",
        "service": "Psychiatrist",
        "condition": "OCD",
        "headline_1_(pinned)": "Experienced OCD Psychiatrists",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Effective OCD Treatment Plan",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |   ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Whitefield Clinic on Old Airport Road",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/ocd/wf",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our expert psychiatrists.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized OCD diagnosis\nCustomized treatment plans, including medication management\nSafe and confidential consultations",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    },
    "psychologist": {
      "anxiety": {
        "adgroup": "Whitefield - Psychologist - Anxiety",
        "campaign": "IO_Whitefield",
        "service": "Psychologist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Psychologists | Anxiety Relief",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/anxiety/wf",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert psychiatrists.\n",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized anxiety diagnosis\nClinical Assessments\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Whitefield - Psychologist - Depression",
        "campaign": "IO_Whitefield",
        "service": "Psychologist",
        "condition": "Depression",
        "headline_1_(pinned)": "Psychologists for Depression.",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/depression/wf",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our experienced psychologists.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized depression diagnosis\nClinical Assessments\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "Whitefield - Psychologist - General",
        "campaign": "IO_Whitefield",
        "service": "Psychologist",
        "condition": "General",
        "headline_1_(pinned)": "Expert Psychologists for You",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team is there for you at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/general/wf",
        "lp_hero_title": "Are you looking for an experienced psychologist?",
        "lp_hero_subtitle": "Experience personalized care from our expert psychologists for various mental health challenges.\n\nWe help with:\nAnxiety | Depression | OCD | Sleep Disorders | Trauma | PTSD | ADHD\nand more. ",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized condition diagnosis\nClinical Assessments\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Whitefield - Psychologist - OCD",
        "campaign": "IO_Whitefield",
        "service": "Psychologist",
        "condition": "OCD",
        "headline_1_(pinned)": "Expert Psychologists for OCD.",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Whitefield Clinic on Old Airport Road",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/ocd/wf",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our expert psychologists.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized OCD diagnosis\nClinical Assessments\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    },
    "therapist": {
      "anxiety": {
        "adgroup": "Whitefield - Therapist - Anxiety",
        "campaign": "IO_Whitefield",
        "service": "Therapist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Therapists for Anxiety Help.",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/anxiety/wf",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our experienced therapists.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized anxiety diagnosis\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Whitefield - Therapist - Depression",
        "campaign": "IO_Whitefield",
        "service": "Therapist",
        "condition": "Depression",
        "headline_1_(pinned)": "Expert Therapists | Depression",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/depression/wf",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert therapists.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized depression diagnosis\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "Whitefield - Therapist - General",
        "campaign": "IO_Whitefield",
        "service": "Therapist",
        "condition": "General",
        "headline_1_(pinned)": "Experienced Therapists for You",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team is there for you at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/general/wf",
        "lp_hero_title": "Are you looking for an experienced therapist?",
        "lp_hero_subtitle": "Experience personalized care from our compassionate therapists for various mental health challenges.\n\nWe help with:\nAnxiety | Depression | OCD | Sleep Disorders | Trauma | PTSD | ADHD\nand more.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized condition diagnosis\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Whitefield - Therapist - OCD",
        "campaign": "IO_Whitefield",
        "service": "Therapist",
        "condition": "OCD",
        "headline_1_(pinned)": "Dedicated Therapist | OCD Care",
        "headline_2_(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Whitefield Clinic on Old Airport Road",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/ocd/wf",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our dedicated therapists.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.\n",
        "hero_description_what_we_offer": "Our therapists provide:\nPersonalized OCD diagnosis\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      }
    }
  }
};


export  {adsPageContent}
