const adsPageContent = {
  "gk": {
    "general": {
      "anxiety": {
        "adgroup": "GK - General - Anxiety",
        "campaign": "IO_Delhi",
        "service": "General",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Experts in Anxiety Relief",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/anxiety/gk",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized anxiety diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed\n",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "GK - General - Depression",
        "campaign": "IO_Delhi",
        "service": "General",
        "condition": "Depression",
        "headline_1_(pinned)": "Depression Experts for you",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/depression/gk",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert clinical team.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized depression diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "GK - General - OCD",
        "campaign": "IO_Delhi",
        "service": "General",
        "condition": "OCD",
        "headline_1_(pinned)": "Experienced in Treating OCD",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/ocd/gk",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our dedicated clinical team.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized OCD diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "GK - General - Depression&Anxiety",
        "campaign": "IO_Delhi",
        "service": "General",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/depression-anxiety/gk",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized depression and anxiety diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "GK - General - ADHD",
        "campaign": "IO_Delhi",
        "service": "General",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "ADHD Care Specialists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/ADHD/gk",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, rediscover your strengths. Recieve ADHD care tailored for you.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized ADHD Diagnosis\nSafe and compassionate care\nNeurofeedback\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }
    },
    "psychiatrist": {
      "anxiety": {
        "adgroup": "GK - Psychiatrist - Anxiety",
        "campaign": "IO_Delhi",
        "service": "Psychiatrist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Psychiatrists | Anxiety Relief",
        "headline_2_pinned": "GK1, Delhi | Rs.1800 / session",
        "headline_3": "Expert Anxiety Treatment",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |   ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/anxiety/gk",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert psychiatrists.<br>",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our experienced psychiatrists provide:\nPersonalized anxiety diagnosis\nCustomized treatment plans including medication if needed\nSafe and confidential consultations",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "GK - Psychiatrist - Depression",
        "campaign": "IO_Delhi",
        "service": "Psychiatrist",
        "condition": "Depression",
        "headline_1_(pinned)": "Psychiatrists for Depression.",
        "headline_2_pinned": "GK1, Delhi | Rs.1800 / session",
        "headline_3": "Effective Depression Treatment",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |    ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/depression/gk",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our experienced psychiatrists.<br>",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized depression diagnosis\nCustomized treatment plans, including medication management\nSafe and confidential consultations",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "GK - Psychiatrist - General",
        "campaign": "IO_Delhi",
        "service": "Psychiatrist",
        "condition": "General",
        "headline_1_(pinned)": "Experienced Psychiatrists",
        "headline_2_pinned": "GK1, Delhi | Rs.1800 / session",
        "headline_3": "Expertise for Every Condition",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |    ",
        "description_2__(pinned)": "Whatever your needs, our team supports you at our Greater Kailash Clinic in Delhi NCR",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/general/gk",
        "lp_hero_title": `Psychiatrists
        in Greater Kailash, Delhi`,
        "lp_hero_subtitle": `Struggling with depression, anxiety, or other mental health concerns? 

Our psychiatrists are located in Greater Kailash 1, South Delhi, conveniently accessible from Hauz Khas, Saket, and surrounding areas near you. 

<b>Get started by booking a consultation today</b>`,
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        // "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized condition diagnosis\nCustomized treatment plans, including medication if needed\nSafe and confidential consultations",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "GK - Psychiatrist - OCD",
        "campaign": "IO_Delhi",
        "service": "Psychiatrist",
        "condition": "OCD",
        "headline_1_(pinned)": "Experienced OCD Psychiatrists",
        "headline_2_pinned": "GK1, Delhi | Rs.1800 / session",
        "headline_3": "Effective OCD Treatment Plan",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |    ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/ocd/gk",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our expert psychiatrists.<br>",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized OCD diagnosis\nCustomized treatment plans, including medication management\nSafe and confidential consultations",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "GK - Psychiatrist - Depression&Anxiety",
        "campaign": "IO_Delhi",
        "service": "Psychiatrist",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "GK1, Delhi | Rs.1800 / session",
        "headline_3": "",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/depression-anxiety/gk",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized depression and anxiety diagnosis\nCustomized treatment plans, including medication management\nSafe and confidential consultations",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "GK - Psychiatrist - ADHD",
        "campaign": "IO_Delhi",
        "service": "Psychiatrist",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2_pinned": "GK1, Delhi | Rs.1800 / session",
        "headline_3": "ADHD Treatment Experts",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/ADHD/gk",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, rediscover your strengths. Recieve ADHD care tailored for you.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized ADHD Diagnosis\nCustomized treatment plans, including medication management\nNeurofeedback\nSafe and confidential consultations",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }
    },
    "psychologist": {
      "anxiety": {
        "adgroup": "GK - Psychologist - Anxiety",
        "campaign": "IO_Delhi",
        "service": "Psychologist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Psychologists | Anxiety Relief",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/anxiety/gk",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert psychologists.<br>",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized anxiety diagnosis\nClinical Assessments\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "GK - Psychologist - Depression",
        "campaign": "IO_Delhi",
        "service": "Psychologist",
        "condition": "Depression",
        "headline_1_(pinned)": "Psychologists for Depression.",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/depression/gk",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our experienced psychologists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized depression diagnosis\nClinical Assessments\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "GK - Psychologist - General",
        "campaign": "IO_Delhi",
        "service": "Psychologist",
        "condition": "General",
        "headline_1_(pinned)": "Expert Psychologists for You",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team supports you at our Greater Kailash Clinic in Delhi NCR",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/general/gk",
        "lp_hero_title": `Psychologists
 in Greater Kailash, Delhi`,
        "lp_hero_subtitle": `Need someone to talk to about life's challenges?
Our experienced psychologists are in Greater Kailash 1(South Delhi), a short distance from Hauz Khas, Defence Colony, and Saket.
With MindfulTMS you recieve professional therapy in a safe, non-judgmental space right in GK1.
Support for anxiety, depression, stress, relationships, trauma and life transitions.

<b>Get started by booking a consultation today</b>`,
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        // "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized condition diagnosis\nClinical Assessments\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "GK - Psychologist - OCD",
        "campaign": "IO_Delhi",
        "service": "Psychologist",
        "condition": "OCD",
        "headline_1_(pinned)": "Expert Psychologists for OCD.",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/ocd/gk",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our expert psychologists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized OCD diagnosis\nClinical Assessments\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "GK - Psychologist - Depression&Anxiety",
        "campaign": "IO_Delhi",
        "service": "Psychologist",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/depression-anxiety/gk",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized depression and anxiety diagnosis\nClinical Assessments\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "GK - Psychologist - ADHD",
        "campaign": "IO_Delhi",
        "service": "Psychologist",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "ADHD Care Specialists",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/ADHD/gk",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, rediscover your strengths. Recieve ADHD care tailored for you.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized ADHD Diagnosis\nClinical Assessments\nCBT and various forms of therapy\nNeurofeedback\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }
    },
    "therapist": {
      "anxiety": {
        "adgroup": "GK - Therapist - Anxiety",
        "campaign": "IO_Delhi",
        "service": "Therapist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Therapists for Anxiety Help.",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/anxiety/gk",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Find lasting relief from anxiety with our experienced counselling therapists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized anxiety diagnosis\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "GK - Therapist - Depression",
        "campaign": "IO_Delhi",
        "service": "Therapist",
        "condition": "Depression",
        "headline_1_(pinned)": "Expert Therapists | Depression",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/depression/gk",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert counselling therapists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized depression diagnosis\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "GK - Therapist - General",
        "campaign": "IO_Delhi",
        "service": "Therapist",
        "condition": "General",
        "headline_1_(pinned)": "Experienced Therapists for You",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team supports you at our Greater Kailash Clinic in Delhi NCR",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/general/gk",
        "lp_hero_title": `Therapists
 in Greater Kailash, Delhi`,
        "lp_hero_subtitle": `Need someone to talk to about life's challenges?
Our experienced therapists are in Greater Kailash 1(South Delhi), a short distance from Hauz Khas, Defence Colony, and Saket. 
With MindfulTMS you recieve professional therapy in a safe, non-judgmental space right in GK1.
Support for anxiety, depression, stress, relationships, trauma and life transitions.

<b>Get started by booking a consultation today</b>`,
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        // "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized condition diagnosis\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "GK - Therapist - OCD",
        "campaign": "IO_Delhi",
        "service": "Therapist",
        "condition": "OCD",
        "headline_1_(pinned)": "Dedicated Therapist | OCD Care",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/ocd/gk",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Receive personalized care for your OCD with our dedicated counselling therapists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized OCD diagnosis\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "GK - Therapist - Depression&Anxiety",
        "campaign": "IO_Delhi",
        "service": "Therapist",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/depression-anxiety/gk",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert counselling therapists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized depression and anxiety diagnosis\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "GK - Therapist - ADHD",
        "campaign": "IO_Delhi",
        "service": "Therapist",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2_pinned": "GK1, Delhi | Rs.1800-2500 / hr",
        "headline_3": "ADHD Care Specialists",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Greater Kailash Clinic in South Delhi.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/ADHD/gk",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, and find your strengths. Recieve ADHD care tailored for you by our experienced counselling therapists.",
        "hero_description_2": "Our Clinic is located in Greater Kailash 1, South Delhi—just a 10–15 minute ride from nearby Hauz Khas and Saket Metro Stations",
        "hero_description_what_we_offer": "Our therapists (clinical psychologists) provide:\nPersonalized ADHD Diagnosis\nClinical Assessments\nCBT and various forms of therapy\nNeurofeedback\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }
    }
  },
  "hb": {
    "general": {
      "anxiety": {
        "adgroup": "Hebbal - General - Anxiety",
        "campaign": "IO_Hebbal",
        "service": "General",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Experts in Anxiety Relief",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with anxiety at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/general/anxiety/hb",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized anxiety diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed\n",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Hebbal - General - Depression",
        "campaign": "IO_Hebbal",
        "service": "General",
        "condition": "Depression",
        "headline_1_(pinned)": "Depression Experts for you",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/general/depression/hb",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert clinical team.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized depression diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Hebbal - General - OCD",
        "campaign": "IO_Hebbal",
        "service": "General",
        "condition": "OCD",
        "headline_1_(pinned)": "Experienced in Treating OCD",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/general/ocd/hb",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our dedicated clinical team.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized OCD diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "Hebbal - General - Depression&Anxiety",
        "campaign": "IO_Hebbal",
        "service": "General",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/general/depression-anxiety/hb",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized depression and anxiety diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "Hebbal - General - ADHD",
        "campaign": "IO_Hebbal",
        "service": "General",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "ADHD Care Specialists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/general/ADHD/hb",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, rediscover your strengths. Recieve ADHD care tailored for you.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized ADHD Diagnosis\nSafe and compassionate care\nNeurofeedback\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }

    },
    "psychologist": {
      "anxiety": {
        "adgroup": "Hebbal - Psychologist - Anxiety",
        "campaign": "IO_Hebbal",
        "service": "Psychologist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Psychologists | Anxiety Relief",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/anxiety/hb",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert psychologists.<br>",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized anxiety diagnosis\nClinical Assessments\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Hebbal - Psychologist - Depression",
        "campaign": "IO_Hebbal",
        "service": "Psychologist",
        "condition": "Depression",
        "headline_1_(pinned)": "Psychologists for Depression.",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/depression/hb",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our experienced psychologists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized depression diagnosis\nClinical Assessments\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "Hebbal - Psychologist - General",
        "campaign": "IO_Hebbal",
        "service": "Psychologist",
        "condition": "General",
        "headline_1_(pinned)": "Expert Psychologists for You",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team is there for you at our Hebbal Clinic in Aster CMI Hospital.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/general/hb",
        "lp_hero_title": "Are you looking for an experienced psychologist?",
        "lp_hero_subtitle": "Experience personalized care from our expert psychologists for various mental health challenges.<br><br><b>We help with:</b><br>Anxiety | Depression | OCD | Sleep Disorders | Trauma | PTSD | ADHD<br>and more. ",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized condition diagnosis\nClinical Assessments\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Hebbal - Psychologist - OCD",
        "campaign": "IO_Hebbal",
        "service": "Psychologist",
        "condition": "OCD",
        "headline_1_(pinned)": "Expert Psychologists for OCD.",
        "headline_2_pinned": "Hebbal (AsterCMI) | Rs1800/hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/ocd/hb",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our expert psychologists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized OCD diagnosis\nClinical Assessments\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "Hebbal - Psychologist - Depression&Anxiety",
        "campaign": "IO_Hebbal",
        "service": "Psychologist",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/depression-anxiety/hb",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized depression and anxiety diagnosis\nClinical Assessments\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "Hebbal - Psychologist - ADHD",
        "campaign": "IO_Hebbal",
        "service": "Psychologist",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2__(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "ADHD Care Specialists",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/ADHD/hb",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, rediscover your strengths. Recieve ADHD care tailored for you.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized ADHD Diagnosis\nClinical Assessments\nCBT and various forms of therapy\nNeurofeedback\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }
    },
    "therapist": {
      "anxiety": {
        "adgroup": "Hebbal - Therapist - Anxiety",
        "campaign": "IO_Hebbal",
        "service": "Therapist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Therapists for Anxiety Help.",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/anxiety/hb",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Find lasting relief from anxiety with our experienced counselling therapists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized anxiety diagnosis\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Hebbal - Therapist - Depression",
        "campaign": "IO_Hebbal",
        "service": "Therapist",
        "condition": "Depression",
        "headline_1_(pinned)": "Expert Therapists | Depression",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/depression/hb",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert counselling therapists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized depression diagnosis\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "Hebbal - Therapist - General",
        "campaign": "IO_Hebbal",
        "service": "Therapist",
        "condition": "General",
        "headline_1_(pinned)": "Experienced Therapists for You",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team is there for you at our Hebbal Clinic in Aster CMI Hospital.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/general/hb",
        "lp_hero_title": "Are you looking for an experienced counselling therapist?",
        "lp_hero_subtitle": "Receive personalized care from our compassionate counselling therapists for various mental health challenges.<br><br><b>We help with:</b><br>Anxiety | Depression | OCD | Sleep Disorders | Trauma | PTSD | ADHD<br>and more.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized condition diagnosis\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Hebbal - Therapist - OCD",
        "campaign": "IO_Hebbal",
        "service": "Therapist",
        "condition": "OCD",
        "headline_1_(pinned)": "Dedicated Therapist | OCD Care",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/ocd/hb",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Receive personalized care for your OCD with our dedicated counselling therapists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized OCD diagnosis\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "Hebbal - Therapist - Depression&Anxiety",
        "campaign": "IO_Hebbal",
        "service": "Therapist",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/depression-anxiety/hb",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert counselling therapists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized depression and anxiety diagnosis\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "Hebbal - Therapist - ADHD",
        "campaign": "IO_Hebbal",
        "service": "Therapist",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2__(pinned)": "In Hebbal AsterCMI | Rs1800/hr",
        "headline_3": "ADHD Care Specialists",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Hebbal Clinic inside Aster CMI Hospital",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/ADHD/hb",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, and find your strengths. Recieve ADHD care tailored for you by our experienced counselling therapists.",
        "hero_description_2": "Our Clinic is located inside Aster CMI Hospital in Hebbal (Sahakar Nagar)",
        "hero_description_what_we_offer": "Our therapists (clinical psychologists) provide:\nPersonalized ADHD Diagnosis\nClinical Assessments\nCBT and various forms of therapy\nNeurofeedback\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }
    },

  },
  "wf": {
    "general": {
      "anxiety": {
        "adgroup": "Whitefield - General - Anxiety",
        "campaign": "IO_Whitefield",
        "service": "General",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Experts in Anxiety Relief",
        "headline_2_pinned": "Whitefield Clinic | Rs1750/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/anxiety/wf",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized anxiety diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed\n",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Whitefield - General - Depression",
        "campaign": "IO_Whitefield",
        "service": "General",
        "condition": "Depression",
        "headline_1_(pinned)": "Depression Experts for you",
        "headline_2_pinned": "Whitefield Clinic | Rs1750/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/depression/wf",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert clinical team.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized depression diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Whitefield - General - OCD",
        "campaign": "IO_Whitefield",
        "service": "General",
        "condition": "OCD",
        "headline_1_(pinned)": "Experienced in Treating OCD",
        "headline_2_pinned": "Whitefield Clinic | Rs1750/hr",
        "headline_3": "Psychologists & Psychiatrists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Whitefield Clinic on Old Airport Road",
        "new_landing_page_url": "https://mindfultms.in/ads/general/ocd/wf",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our dedicated clinical team.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized OCD diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "Whitefield - General - Depression&Anxiety",
        "campaign": "IO_Whitefield",
        "service": "General",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "Whitefield Clinic | Rs1750/hr",
        "headline_3": "",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/depression-anxiety/wf",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized depression and anxiety diagnosis\nSafe and compassionate care\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "Whitefield - General - ADHD",
        "campaign": "IO_Whitefield",
        "service": "General",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2__(pinned)": "Whitefield Clinic | Rs1750/hr",
        "headline_3": "ADHD Care Specialists",
        "description_1__(pinned)": "30 min sessions with Psychiatrists | 1 hr sessions with Psychologists  | In‑Clinic Only |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/general/ADHD/wf",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, rediscover your strengths. Recieve ADHD care tailored for you.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our experts provide:\nPersonalized ADHD Diagnosis\nSafe and compassionate care\nNeurofeedback\nConfidentiality\n\nPsychiatrists offer customized treatment plans including medication, if needed",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }
    },
    "psychiatrist": {
      "anxiety": {
        "adgroup": "Whitefield - Psychiatrist - Anxiety",
        "campaign": "IO_Whitefield",
        "service": "Psychiatrist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Psychiatrists | Anxiety Relief",
        "headline_2_pinned": "Whitefield Clinic | Rs2000/hr",
        "headline_3": "Expert Anxiety Treatment",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |    ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/anxiety/wf",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert psychiatrists.<br>",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our experienced psychiatrists provide:\nPersonalized anxiety diagnosis\nCustomized treatment plans including medication if needed\nSafe and confidential consultations",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Whitefield - Psychiatrist - Depression",
        "campaign": "IO_Whitefield",
        "service": "Psychiatrist",
        "condition": "Depression",
        "headline_1_(pinned)": "Psychiatrists for Depression.",
        "headline_2_pinned": "Whitefield Clinic | Rs2000/hr",
        "headline_3": "Effective Depression Treatment",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |    ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/depression/wf",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our experienced psychiatrists.<br>",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized depression diagnosis\nCustomized treatment plans, including medication management\nSafe and confidential consultations",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "Whitefield - Psychiatrist - General",
        "campaign": "IO_Whitefield",
        "service": "Psychiatrist",
        "condition": "General",
        "headline_1_(pinned)": "Experienced Psychiatrists",
        "headline_2_pinned": "Whitefield Clinic | Rs2000/hr",
        "headline_3": "Expertise for Every Condition",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |    ",
        "description_2__(pinned)": "Whatever your needs, our team is there for you at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/general/wf",
        "lp_hero_title":`Psychiatrists
 in Whitefield, Bangalore`,
        "lp_hero_subtitle": `Struggling with depression, anxiety, or other concerns? Get professional psychiatric assistance close to your location.
Our experienced psychiatrists are located in Whitefield, easily accessible from Marathahalli, Brookefield, and Varthur.

<b>Get started by booking a consultation today</b>`,
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        // "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized condition diagnosis\nCustomized treatment plans, including medication if needed\nSafe and confidential consultations",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Whitefield - Psychiatrist - OCD",
        "campaign": "IO_Whitefield",
        "service": "Psychiatrist",
        "condition": "OCD",
        "headline_1_(pinned)": "Experienced OCD Psychiatrists",
        "headline_2_pinned": "Whitefield Clinic | Rs2000/hr",
        "headline_3": "Effective OCD Treatment Plan",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |    ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Whitefield Clinic on Old Airport Road",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/ocd/wf",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our expert psychiatrists.<br>",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized OCD diagnosis\nCustomized treatment plans, including medication management\nSafe and confidential consultations",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "Whitefield - Psychiatrist - Depression&Anxiety",
        "campaign": "IO_Whitefield",
        "service": "Psychiatrist",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "Whitefield Clinic | Rs2000/hr",
        "headline_3": "",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/depression-anxiety/wf",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized depression and anxiety diagnosis\nCustomized treatment plans, including medication management\nSafe and confidential consultations",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "Whitefield - Psychiatrist - ADHD",
        "campaign": "IO_Whitefield",
        "service": "Psychiatrist",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2__(pinned)": "Whitefield Clinic | Rs2000/hr",
        "headline_3": "ADHD Treatment Experts",
        "description_1__(pinned)": "Book your 30‑min session now.    | In‑Clinic Only |    Safe and confidential space   |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychiatrist/ADHD/wf",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, rediscover your strengths. Recieve ADHD care tailored for you.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our psychiatrists provide:\nPersonalized ADHD Diagnosis\nCustomized treatment plans, including medication management\nNeurofeedback\nSafe and confidential consultations",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }
    },
    "psychologist": {
      "anxiety": {
        "adgroup": "Whitefield - Psychologist - Anxiety",
        "campaign": "IO_Whitefield",
        "service": "Psychologist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Psychologists | Anxiety Relief",
        "headline_2_pinned": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/anxiety/wf",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Regain control and find lasting relief from anxiety with our expert psychologists.<br>",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized anxiety diagnosis\nClinical Assessments\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Whitefield - Psychologist - Depression",
        "campaign": "IO_Whitefield",
        "service": "Psychologist",
        "condition": "Depression",
        "headline_1_(pinned)": "Psychologists for Depression.",
        "headline_2_pinned": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/depression/wf",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our experienced psychologists.<br>",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized depression diagnosis\nClinical Assessments\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "Whitefield - Psychologist - General",
        "campaign": "IO_Whitefield",
        "service": "Psychologist",
        "condition": "General",
        "headline_1_(pinned)": "Expert Psychologists for You",
        "headline_2_pinned": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team is there for you at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/general/wf",
        "lp_hero_title": `	
Psychologists
 in Whitefield, Bangalore`,
        "lp_hero_subtitle": `Need someone to talk to about life's challenges?
Our experienced therapists are located in Whitefield, conveniently located for residents of Marathahalli, Old Airport Road, Brookefield, and Varthur.
With MindfulTMS you recieve professional therapy in a safe, non-judgmental space right in Whitefield.
Support for anxiety, depression, stress, relationships, trauma and life transitions.

<b>Get started by booking a consultation today</b>`,"hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        // "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized condition diagnosis\nClinical Assessments\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Whitefield - Psychologist - OCD",
        "campaign": "IO_Whitefield",
        "service": "Psychologist",
        "condition": "OCD",
        "headline_1_(pinned)": "Expert Psychologists for OCD.",
        "headline_2_pinned": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Whitefield Clinic on Old Airport Road",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/ocd/wf",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Experience personalized care to beat OCD with our expert psychologists.<br>",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized OCD diagnosis\nClinical Assessments\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "Whitefield - Psychologist - Depression&Anxiety",
        "campaign": "IO_Whitefield",
        "service": "Psychologist",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/depression-anxiety/wf",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert clinical team.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized depression and anxiety diagnosis\nClinical Assessments\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "Whitefield - Psychologist - ADHD",
        "campaign": "IO_Whitefield",
        "service": "Psychologist",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2__(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "ADHD Care Specialists",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/psychologist/ADHD/wf",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, rediscover your strengths. Recieve ADHD care tailored for you.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our clinical psychologists provide:\nPersonalized ADHD Diagnosis\nClinical Assessments\nCBT and various forms of therapy\nNeurofeedback\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }

    },
    "therapist": {
      "anxiety": {
        "adgroup": "Whitefield - Therapist - Anxiety",
        "campaign": "IO_Whitefield",
        "service": "Therapist",
        "condition": "Anxiety",
        "headline_1_(pinned)": "Therapists for Anxiety Help.",
        "headline_2_pinned": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Find Your Calm Amid Anxiety",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your anxiety at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/anxiety/wf",
        "lp_hero_title": "Is Anxiety Disrupting Your Peace of Mind?",
        "lp_hero_subtitle": "Find lasting relief from anxiety with our experienced counselling therapists.<br>",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized anxiety diagnosis\nCBT, relaxation training and various forms of therpy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Anxiety Symptoms",
        "hero_image": ""
      },
      "depression": {
        "adgroup": "Whitefield - Therapist - Depression",
        "campaign": "IO_Whitefield",
        "service": "Therapist",
        "condition": "Depression",
        "headline_1_(pinned)": "Expert Therapists | Depression",
        "headline_2_pinned": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Finding Light in Depression",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/depression/wf",
        "lp_hero_title": "Is Depression Making Life Harder Than It Should Be?",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life from depression with our expert counselling therapists.<br>",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized depression diagnosis\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "Depression Symptoms",
        "hero_image": ""
      },
      "general": {
        "adgroup": "Whitefield - Therapist - General",
        "campaign": "IO_Whitefield",
        "service": "Therapist",
        "condition": "General",
        "headline_1_(pinned)": "Experienced Therapists for You",
        "headline_2_pinned": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Caring for Every Condition",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Whatever your needs, our team is there for you at our Whitefield Clinic on Old Airport Rd.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/general/wf",
        "lp_hero_title": `Therapists 
        in Whitefield, Bangalore`,
        "lp_hero_subtitle": `Need someone to talk to about life's challenges?
Our experienced therapists are located in Whitefield, conveniently located for residents of Marathahalli, Old Airport Road, Brookefield, and Varthur.

With MindfulTMS you recieve professional therapy in a safe, non-judgmental space right in Whitefield. 
Support for anxiety, depression, stress, relationships, trauma and life transitions.

<b>Get started by booking a consultation today</b>`,
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        // "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized condition diagnosis\nCBT, DBT, ACT and a range of therapies\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "What We Treat",
        "hero_image": ""
      },
      "ocd": {
        "adgroup": "Whitefield - Therapist - OCD",
        "campaign": "IO_Whitefield",
        "service": "Therapist",
        "condition": "OCD",
        "headline_1_(pinned)": "Dedicated Therapist | OCD Care",
        "headline_2_pinned": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "Empower Your OCD Recovery",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |     ",
        "description_2__(pinned)": "Trust our team to help you with your OCD at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/ocd/wf",
        "lp_hero_title": "Is OCD Controlling Your Life?",
        "lp_hero_subtitle": "Receive personalized care for your OCD with our dedicated counselling therapists.<br>",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized OCD diagnosis\nERP Therapy and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "OCD Symptoms",
        "hero_image": ""
      },
      "depression-anxiety": {
        "adgroup": "Whitefield - Therapist - Depression&Anxiety",
        "campaign": "IO_Whitefield",
        "service": "Therapist",
        "condition": "Depression & Anxiety",
        "lp_hero_title": "Dealing with Depression & Anxiety?",
        "headline_2_pinned": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with depression at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/depression-anxiety/wf",
        "lp_hero_subtitle": "Rediscover hope and reclaim your life. Fight depression and anxiety with our expert counselling therapists.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_12": "",
        "hero_description_what_we_offer": "Our counselling therapists provide:\nPersonalized depression and anxiety diagnosis\nCBT and various forms of therapy\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "",
        "hero_image": ""
      },
      "adhd": {
        "adgroup": "Whitefield - Therapist - ADHD",
        "campaign": "IO_Whitefield",
        "service": "Therapist",
        "condition": "ADHD",
        "headline_1_(pinned)": "Expert ADHD Support",
        "headline_2__(pinned)": "Whitefield Clinic | Rs1800/hr",
        "headline_3": "ADHD Care Specialists",
        "description_1__(pinned)": "Book your 1 hour session now.    | In‑Clinic Only |    Safe and confidential space  |",
        "description_2__(pinned)": "Trust our team to help you with your ADHD at our Whitefield Clinic on Old Airport Road.",
        "new_landing_page_url": "https://mindfultms.in/ads/therapist/ADHD/wf",
        "lp_hero_title": "Need help with ADHD?",
        "lp_hero_subtitle": "Overcome distractions, and find your strengths. Recieve ADHD care tailored for you by our experienced counselling therapists.",
        "hero_description_2": "Our Clinic is located on Old Airport Road in Whitefield, conveniently accessible from nearby areas of Marthahalli, Brookefield and Varthur.",
        "hero_description_what_we_offer": "Our therapists (clinical psychologists) provide:\nPersonalized ADHD Diagnosis\nClinical Assessments\nCBT and various forms of therapy\nNeurofeedback\nSafe and compassionate care\nConfidentiality",
        "block_to_show": "ADHD Symptoms",
        "hero_image": ""
      }
    }
  }
};



function formatDescription(desc) {
  // split header, list items, and trailing text
  const [headerAndItems, ...rest] = desc.split('\n\n');
  const lines = headerAndItems.split('\n');
  const header = lines[0].replace(/:$/, ''); // remove trailing colon
  const items = lines.slice(1);

  const listHtml = items.map(item => `                  <li>${item}</li>`).join('\n');

  const trailing = rest.join('\n\n'); // everything after the blank line

  return (
    `<b>${header}:</b><br />
                <ul class="list-disc text-base pl-6 mb-4">
${listHtml}
                </ul>

               <p class="text-base">${trailing}</p>`
  );
}

//
// Deep‑walk through the entire adsPageContent object and
// replace only the hero_description_what_we_offer values.
// The rest of the data remains byte‑for‑byte the same.
//
function applyHtmlFormatting(obj) {
  if (Array.isArray(obj)) {
    return obj.map(applyHtmlFormatting);
  } else if (obj && typeof obj === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(obj)) {
      if (k === 'hero_description_what_we_offer' && typeof v === 'string') {
        out[k] = formatDescription(v);
      } else {
        out[k] = applyHtmlFormatting(v);
      }
    }
    return out;
  } else {
    return obj;
  }
}

const adsPageContentFormatted = applyHtmlFormatting(adsPageContent);

export { adsPageContentFormatted as adsPageContent };
// export { adsPageContent };
